title: Grupo Turing
description: Grupo de estudos
author: Grupo Turing
logo: ../static/img/gturing-logo.jpg
github: https://github.com/grupoturing
about: Grupo de estudos

baseurl: ""
url: "http://aboutashu.com/hcz-jekyll-blog"

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
